version: '3'

services:
  php-apache: # apache-php+php as same component. Dynamic part of service
    container_name: apache-php
    build: apache-php
    volumes:
      - ./apache-php/src:/var/www/html-dynamic
    ports:
      - "8081:8081"
  nginx: # static content
    container_name: nginx
    build: nginx
    volumes:
      - ./nginx/src:/usr/share/nginx/html-static
    ports:
      - "8082:8082"
  mysql:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appDb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./db/init.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql
    ports:
      - "3306:3306"