version: "3.8"

services:
  db:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./server:/docker-entrypoint-initdb.d
    container_name: rscir_pr2_db
  server:
    build: ./server
    restart: always
    volumes:
      - ./server:/var/www/html/
    ports:
      - "8081:80"
    container_name: rscir_pr2_server